#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

touch $install_dir/database.db

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
chmod +x "$install_dir/filebrowser"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Web File Browser" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="settings.json" --destination="$install_dir/settings.json"

#=================================================
# ADD A USER
#=================================================
ynh_script_progression "Adding $app's admin user..."

pushd "$install_dir"
 	ynh_exec_as_app ./filebrowser -c settings.json config init
	ynh_exec_as_app ./filebrowser -c settings.json users add $admin $password --perm.admin --locale=$locale
	ynh_exec_as_app ./filebrowser -c settings.json config set --auth.method=noauth
popd

#=================================================
# ADD A NFS SHARE
#=================================================
#Adding the datadir directory as an NFS share
ynh_exec_and_print_stderr_only_if_error cat "$data_dir 127.0.0.1(rw,sync,no_subtree_check)" >> /etc/exports
ynh_exec_and_print_stderr_only_if_error exportfs -a
ynh_exec_and_print_stderr_only_if_error systemctl restart nfs-kernel-server

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
